# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6aNUt_h51FxlZgUBEEVpg8X4LjnvueY
"""

# === 安裝必要套件 ===
#!pip install requests beautifulsoup4 pandas python-docx

import re
import time
import html
import requests
from bs4 import BeautifulSoup
from docx import Document
from docx.shared import Pt, Cm, RGBColor

# ➤ 對 MOMO 商品進行 retry + timeout 的簡易爬蟲
def parse_momo_simple(url, max_retries=3):
    headers = {"User-Agent": "Mozilla/5.0"}
    for attempt in range(1, max_retries + 1):
        try:
            res = requests.get(url, headers=headers, timeout=10)
            res.raise_for_status()
            soup = BeautifulSoup(res.text, "html.parser")

            # 商品名稱
            name = soup.select_one("meta[property='og:title']")
            name = name["content"].strip() if name else "未取得"

            # 品號（多重嘗試）
            prod_no = None
            tag = soup.select_one("#osmPrdNo")
            if tag: prod_no = tag.text.strip()
            if not prod_no:
                li_tags = soup.select("li.tvlogo, li.goods-code-container")
                for tag in li_tags:
                    if "品號：" in tag.text:
                        prod_no = tag.text.split("品號：")[-1].strip()
                        break
            if not prod_no:
                meta_code = soup.select_one("meta[name='keywords']")
                if meta_code and "品號：" in meta_code["content"]:
                    prod_no = meta_code["content"].split("品號：")[-1].split(",")[0].strip()
            if not prod_no:
                match = re.search(r"品號[:： ]?\s*(\w+)", soup.get_text())
                prod_no = match.group(1).strip() if match else "未取得"

            return {
                "商品名稱": name,
                "品號": prod_no,
                "網址": url
            }

        except Exception as e:
            print(f"❌ 第 {attempt} 次失敗：{e}")
            if attempt < max_retries:
                time.sleep(3)
            else:
                return {
                    "商品名稱": f"錯誤：{e}",
                    "品號": "錯誤",
                    "網址": url
                }

# ➤ 擷取網址並處理 &amp; 解碼
def extract_urls_from_text(text):
    clean = html.unescape(html.unescape(text))
    urls = re.findall(r'https?://[^\s\]]+', clean)
    return list(dict.fromkeys(urls))

# ➤ 依「收文號：」切段（多筆來文）
def split_blocks(text):
    parts = re.split(r"(?=收文號：\d+)", text)
    return [part.strip() for part in parts if part.strip()]

# ➤ 萃取標題名稱用來儲存 Word（從第一筆收文號建立）
def extract_filename(text_block):
    match = re.search(r"收文號：(\d+)", text_block)
    return f"收文號{match.group(1)}-查核報告" if match else "查核報告"

# ✅ 請將多筆原始來文資料貼入 raw_text
raw_text = """
收文號：1140057499
來文日期：1141121
來文機關：意見信箱-楊峰源
來文號：2025112100008
受文者：經濟部標準檢驗局台南分局
附件數：3
附件檔名：20251121000081.jpg、20251121000082.jpg、20251121000083.jpg

主旨：市場監督 楊峰源 (申請流水號：1141121000008) 有貼商品安全標章，品質不符規定,字號標示不符 網路平台

說明：

[其他, JBL SOUNDGEAR FRAMES 音樂太陽眼鏡, https://www.momoshop.com.tw/goods/GoodsDetail.jsp?i_code=13772321&amp;amp;Area=search&amp;amp;mdiv=403&amp;amp;oid=1_2&amp;amp;cid=index&amp;amp;kw=%E6%99%BA%E8%83%BD%E7%9C%BC%E9%8F%A1] [其他, SG智慧眼鏡, https://www.momoshop.com.tw/goods/GoodsDetail.jsp?i_code=14033796&amp;amp;Area=search&amp;amp;mdiv=403&amp;amp;oid=1_3&amp;amp;cid=index&amp;amp;kw=%E6%99%BA%E8%83%BD%E7%9C%BC%E9%8F%A1] [其他, 智能AI翻譯眼鏡, https://www.momoshop.com.tw/TP/TP0004865/goodsDetail/TP00048650000033] [其他, 智能AI翻譯眼鏡 ai眼鏡, https://www.momoshop.com.tw/TP/TP0004865/goodsDetail/TP00048650000032] [其他, 台灣發貨 辦公神器 AI智能拍照眼鏡全球翻譯, https://www.momoshop.com.tw/TP/TP0004865/goodsDetail/TP00048650000097]

正本：經濟部標準檢驗局
收文號：1140057500
來文日期：1141121
來文機關：意見信箱-楊峰源
來文號：2025112100009
受文者：經濟部標準檢驗局台南分局
附件數：3
附件檔名：20251121000091.jpg、20251121000092.jpg、20251121000093.jpg

主旨：市場監督 楊峰源 (申請流水號：1141121000009) 未貼商品安全標章,未標示R字軌 網路平台

說明：

[其他, JBL SOUNDGEAR FRAMES 音樂太陽眼鏡, https://www.momoshop.com.tw/goods/GoodsDetail.jsp?i_code=13772338&amp;amp;Area=search&amp;amp;mdiv=403&amp;amp;oid=1_6&amp;amp;cid=index&amp;amp;kw=%E6%99%BA%E8%83%BD%E7%9C%BC%E9%8F%A1] [其他, Xiaomi 智慧音頻眼鏡, https://www.momoshop.com.tw/goods/GoodsDetail.jsp?i_code=13586902&amp;amp;Area=search&amp;amp;mdiv=403&amp;amp;oid=1_1&amp;amp;cid=index&amp;amp;kw=%E6%99%BA%E8%83%BD%E7%9C%BC%E9%8F%A1] [其他, VIVE Eagle 智慧眼鏡, https://www.momoshop.com.tw/TP/TP0006668/goodsDetail/TP00066680000185]

正本：經濟部標準檢驗局



"""

# ✅ 單一 Word 輸出，逐段來文 + 正確插入商品區塊（i 全域遞增 & retry & delay）
doc = Document()
for sec in doc.sections:
    sec.top_margin = Cm(1.27)
    sec.bottom_margin = Cm(1.27)
    sec.left_margin = Cm(1.85)
    sec.right_margin = Cm(1.27)

blocks = split_blocks(raw_text)
global_index = 1  # 🔺 所有段落共用這個商品編號計數器

for block in blocks:
    lines = block.strip().split("\n")
    urls = extract_urls_from_text(block)

    results = []
    for url in urls:
        r = parse_momo_simple(url)  # 已內建 retry & timeout
        r["編號"] = global_index
        global_index += 1
        results.append(r)
        time.sleep(5)

    for line in lines:
        doc.add_paragraph(line.strip())

        # 在「正本：」行之後插入該段對應的商品查核結果
        if line.strip().startswith("正本："):
            for row in results:
                i, name, prod, url = row["編號"], row["商品名稱"], row["品號"], row["網址"]

                p1 = doc.add_paragraph()
                r1 = p1.add_run(f"{i}. {name}")
                r1.font.color.rgb = RGBColor(255, 0, 0)
                r1.font.size = Pt(12)

                p2 = doc.add_paragraph()
                r2 = p2.add_run("(查無商品檢驗標識)")
                r2.font.color.rgb = RGBColor(255, 0, 0)
                r2.font.size = Pt(12)

                doc.add_paragraph(f"品號: {prod}")
                doc.add_paragraph(f"網址: {url}")
                doc.add_paragraph()

# 儲存 Word（使用第一筆段的收文號命名）
fname = extract_filename(blocks[0]) + ".docx"
doc.save(fname)
print("✅ 已產出 Word 檔案：", fname)